{
 "title": "WireGuard",
 "tags": [
  "prometheus",
  "wireguard",
  "network"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(wireguard_latest_handshake_seconds{job=\"wireguard-exporter\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Handshake",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - wireguard_latest_handshake_seconds{node=\"$node\"}",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total{node=\"$node\"}[5m])",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{node=\"$node\"}[5m])",
     "legendFormat": "{{allowed_ips}} ({{friendly_name}})"
    }
   ]
  }
 ]
}